# -*- coding: utf-8 -*-
"""Question-answering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzt-NDXAZjnuhiNp9lIXwyW_9E-pMki3
"""

!pip install -q transformers==4.4.2

!pip install transformers

import torch
torch.__version__

!pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html

from transformers import pipeline
import pandas as pd

tqa = pipeline(task="table-question-answering",model="google/tapas-base-finetuned-wtq")

table=pd.read_csv("/content/dataset.csv")

table = table.astype(str)

table

query = "Which stadium was the match on Monday, 23 October?"
print(tqa(table=table,query=query)["answer"])



